### ISSUE TITLE
ghcr.io/hwameistor/local-storage:tag error

### ISSUE THREAD

**Issue by jiuker** [hwameistor/helm-charts#11]
ghcr.io/hwameistor/local-storage:v0.0.3
```
Error response from daemon: manifest unknown
```
ghcr.io/hwameistor/local-storage:v0.0.1
Will pull succeed

**Comment by niulechuan** [comment]
CC: @buffalo1024 Did you fix this?

**Comment by jiuker** [comment]
> CC: @buffalo1024 Did you fix this?

Done!
