### ISSUE TITLE
Before Install，Exec "kubectl label node xxxx"

### ISSUE THREAD

**Issue by jiuker** [hwameistor/helm-charts#15]
According to the readme file, I need to execute `kubectl label node < node name > “csi.driver. hwameister.io/local-storage = true"`, but I find I still need to execute
```
kubectl label node <node-name> "localstorage.hwameistor.io/local-storage-topology-node=<node-name>"

kubectl label node <node-name> "csi.driver.hwameistor.io/localstorage=true"
```
To meet the podaffinity of hwameister CSI controller
Nodeaffinity of hwameistor.

Are there documents to support it?

**Comment by niulechuan** [comment]
> According to the readme file, I need to execute `kubectl label node < node name > “csi.driver. hwameister.io/local-storage = true"`, but I find I still need to execute
> 
> ```
> kubectl label node <node-name> "localstorage.hwameistor.io/local-storage-topology-node=<node-name>"
> 
> kubectl label node <node-name> "csi.driver.hwameistor.io/localstorage=true"
> ```
> 
> To meet the podaffinity of hwameister CSI controller Nodeaffinity of hwameistor.
> 
> Are there documents to support it?

Thank for file this issue.

We didn't require add ``localstorage.hwameistor.io/local-storage-topology-node=<node-name>``  manually since the local-storage CSI driver will add this autometicly.

``csi.driver.hwameistor.io/localstorage=true`` case a problem, is a typo.

CC: @buffalo1024 could you take look at this?

**Comment by jiuker** [comment]
> > According to the readme file, I need to execute `kubectl label node < node name > “csi.driver. hwameister.io/local-storage = true"`, but I find I still need to execute
> > ```
> > kubectl label node <node-name> "localstorage.hwameistor.io/local-storage-topology-node=<node-name>"
> > 
> > kubectl label node <node-name> "csi.driver.hwameistor.io/localstorage=true"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To meet the podaffinity of hwameister CSI controller Nodeaffinity of hwameistor.
> > Are there documents to support it?
> 
> Thank for file this issue.
> 
> We didn't require add `localstorage.hwameistor.io/local-storage-topology-node=<node-name>` manually since the local-storage CSI driver will add this autometicly.
> 
> `csi.driver.hwameistor.io/localstorage=true` case a problem, is a typo.
> 
> CC: @buffalo1024 could you take look at this?

Yes，It don't need `We didn't require add localstorage.hwameistor.io/local-storage-topology-node=<node-name>`
