### ISSUE TITLE
add  imageRegistry value in helm charts

### ISSUE THREAD

**Issue by yankay** [hwameistor/helm-charts#27]
Like: https://github.com/bitnami/charts/blob/master/bitnami/apache/values.yaml

If there are “imageRegistry" value, it's good for:
* Air-Gap Environment
* Use in China. with https://github.com/DaoCloud/public-image-mirror

**Comment by niulechuan** [comment]
Good idea! we will consider to add it in future release.

**Comment by niulechuan** [comment]
Hi, since we achieved this. I will close this issue. Feel free to reopen it if you have some advise.
