### ISSUE TITLE
Namespace consistency in HwameiStor Deployment

### ISSUE THREAD

**Issue by zhaosimon** [hwameistor/helm-charts#42]
During HwameiStor deployment, first we need to create HwameiStor system namespace. With Helm Charts deployment the namespace created is 'hwameistor':

https://github.com/hwameistor/helm-charts/blob/main/README.md#step-1-install-hwameistor[](https://user-images.githubusercontent.com/36882380/163895294-5699ee0d-bbd4-4f91-aa48-c9bb7be7060b.png)
<img width="390" alt="屏幕快照 2022-04-21 上午11 42 51" src="https://user-images.githubusercontent.com/36882380/164367677-f730f1e9-0c4f-4b4d-9d7a-a207da4cd185.png">

While in the code https://github.com/hwameistor/local-storage/blob/main/deploy/01_namespace.yaml[](https://user-images.githubusercontent.com/36882380/163895384-aafc3a80-107f-4770-b202-d5397d49cb5b.png), the namespace is 'local-storage-system'.
<img width="236" alt="屏幕快照 2022-04-21 上午11 42 58" src="https://user-images.githubusercontent.com/36882380/164367700-4759145b-72dc-4254-bcc6-7cc9137aa5c0.png">

Suggest to make these 2 in consistent.

**Comment by SSmallMonster** [comment]
Fixed at latest version.
