### ISSUE TITLE
Kubernetes version supportability on some HwameiStor CRD (need 1.22.xx over)

### ISSUE THREAD

**Issue by zhaosimon** [hwameistor/helm-charts#43]
Environemnt:

kubelete version 1.18.20
<img width="499" alt="屏幕快照 2022-04-21 上午11 49 39" src="https://user-images.githubusercontent.com/36882380/164368444-ac3249ec-eb6a-4d42-bd49-6c8508488c17.png">

HwameiStor CRDs
![屏幕快照 2022-04-21 上午11 50 55](https://user-images.githubusercontent.com/36882380/164368540-470cfd20-add1-485f-866c-99fab282ac03.png)

Claimed local storage on nodes 90, 91
<img width="490" alt="屏幕快照 2022-04-21 上午11 51 49" src="https://user-images.githubusercontent.com/36882380/164368698-475c28d9-3b9d-4bf6-aab7-9ab1e458d2eb.png">

lsn info
<img width="492" alt="屏幕快照 2022-04-21 上午11 52 59" src="https://user-images.githubusercontent.com/36882380/164368761-e573afab-a9de-4300-b14a-edaccf20cc66.png">

Deployment
<img width="494" alt="屏幕快照 2022-04-21 上午11 53 54" src="https://user-images.githubusercontent.com/36882380/164368924-c9817284-fff2-4140-8979-e49ecb28996d.png">

![屏幕快照 2022-04-21 上午11 55 09](https://user-images.githubusercontent.com/36882380/164368991-ecb8904b-7cbb-4086-811b-18b3c5042cc6.png)

Error massages
<img width="1333" alt="屏幕快照 2022-04-21 上午11 56 45" src="https://user-images.githubusercontent.com/36882380/164369160-38b6a5c9-0a58-4140-be9e-d8be5eb76129.png">

<img width="1089" alt="屏幕快照 2022-04-21 上午11 57 25" src="https://user-images.githubusercontent.com/36882380/164369202-f05e3e7e-74d7-4595-ac88-8968c93619bd.png">

**Comment by SSmallMonster** [comment]
This is a compatibility problem of the scheduler in the old version of k8s (< 1.21.1)

**Comment by zhaosimon** [comment]
so kubernetes v1.18.x/1.21.1 have been tested

support matrix info:
https://dwiki.daocloud.io/pages/viewpage.action?pageId=121169408
